dataset_type: 'with_mutation_dataset'
max_length: 256
n_neighbors: 32
cols_label: ['DDG']
col_valid_chains: 'valid_chains'
col_chainids: 'chainids'
col_partner: 'Partners(A_B)'
col_mutation: 'mutation'
col_protein: 'Protein'
col_wt: 'path_wt'
col_pdb: 'pdb_id'
data_root: './datasets/DMS/LASSA/'
cache_dir: './cache/lassa_dms/'
batch_size: 16
num_workers: 0
pin_memory: True
loss_types:
  - regression
loss_weights:
  - 1.0
transform:
  - type: select_atom
    resolution: full
  - type: selected_region_fixed_size_patch
    select_attr: mut_flag
    patch_size: 128